word_list = [
    'abruptly sudden', 'absurd ridiculous', 'abyss chasm', 'affix attach',
    'askew crooked', 'avenue street', 'awkward clumsy', 'axiom principle',
    'azure sky blue', 'bagpipes musical instrument', 'bandwagon trend',
    'banjo musical instrument', 'bayou marshy outlet', 'beekeeper profession',
    'bikini beachwear', 'blitz swift attack', 'blizzard snowstorm',
    'boggle puzzle', 'bookworm avid reader', 'boxcar train car',
    'boxful container full', 'buckaroo cowboy', 'buffalo animal',
    'buffoon clown', 'buxom full-bosomed', 'buzzard bird of prey',
    'buzzing humming', 'buzzwords trendy terms', 'caliph ruler',
    'cobweb spiderweb', 'cockiness arrogance', 'croquet lawn game',
    'crypt hidden underground chamber', 'curacao liqueur', 'cycle sequence',
    'daiquiri cocktail', 'dirndl traditional dress', 'disavow deny knowledge',
    'dizzying causing dizziness', 'duplex two-part',
    'dwarves small fantasy creatures', 'embezzle steal', 'equip outfit',
    'espionage spying', 'euouae musical term', 'exodus mass departure',
    'faking pretending', 'fishhook curved tool', 'fixable repairable',
    'fjord long narrow inlet', 'flapjack pancake', 'flopping flapping',
    'fluffiness softness', 'flyby passing flight', 'foxglove flowering plant',
    'frazzled exhausted', 'frizzled curled', 'fuchsia purplish-red color',
    'funny humorous', 'gabby talkative', 'galaxy astronomical system',
    'galvanize stimulate', 'gazebo outdoor structure', 'giaour non-believer',
    'gizmo gadget', 'glowworm bioluminescent insect', 'glyph symbol',
    'gnarly twisted', 'gnostic possessing knowledge', 'gossip rumor',
    'grogginess drowsiness', 'haiku Japanese poem', 'haphazard random',
    'hyphen punctuation mark', 'iatrogenic doctor-induced',
    'icebox refrigerator', 'injury harm', 'ivory elephant tusks',
    'ivy climbing plant', 'jackpot big prize', 'jaundice yellowing of skin',
    'jawbreaker hard candy', 'jaywalk cross the road illegally',
    'jazziest most stylish', 'jazzy lively', 'jelly fruit preserve',
    'jigsaw puzzle', 'jinx bring bad luck', 'jiujitsu martial art',
    'jockey horse rider', 'jogging running', 'joking kidding',
    'jovial cheerful', 'joyful happy', 'juicy succulent',
    'jukebox music player', 'jumbo very large', 'kayak small boat',
    'kazoo musical instrument', 'keyhole lock opening',
    'khaki brownish-yellow color', 'kilobyte unit of digital storage',
    'kiosk booth', 'kitsch art of bad taste', 'kiwifruit edible berry',
    'klutz clumsy person', 'knapsack backpack', 'larynx voice box',
    'lengths long distances', 'lucky fortunate', 'luxury indulgence',
    'lymph bodily fluid', 'marquis nobleman', 'matrix grid',
    'megahertz frequency unit', 'microwave kitchen appliance',
    'mnemonic memory aid', 'mystify bewilder', 'naphtha flammable liquid',
    'nightclub entertainment venue', 'nowadays currently',
    'numbskull stupid person', 'nymph mythical creature',
    'onyx black gemstone', 'ovary reproductive organ',
    'oxidize combine with oxygen', 'oxygen essential gas', 'pajama sleepwear',
    'peekaboo game', 'phlegm thick mucus', 'pixel picture element',
    'pizazz lively style', 'pneumonia lung infection', 'polka dance',
    'pshaw expression of disgust', 'psyche mind', 'puppy young dog',
    'puzzling confusing', 'quartz mineral', 'queue waiting line',
    'quips witty remarks', 'quixotic idealistic', 'quiz test',
    'quizzes plural of quiz', 'quorum minimum number',
    'razzmatazz noisy excitement', 'rhubarb edible plant',
    'rhythm musical beat', 'rickshaw two-wheeled cart',
    'schnapps alcoholic beverage', 'scratch scrape', 'shiv makeshift knife',
    'snazzy stylish', 'sphinx mythological creature', 'spritz spray',
    'squawk loud cry', 'staff group of people', 'strength power',
    'strengths strong points', 'stretch extend', 'stronghold fortified place',
    'stymied obstructed', 'subway underground transport', 'swivel rotate',
    'syndrome group of symptoms', 'thriftless wasteful',
    'thumbscrew torture instrument', 'topaz gemstone',
    'transcript written record', 'transgress violate rules',
    'transplant relocate', 'triphthong three vowel sounds', 'twelfth 12th',
    'twelfths 12 equal parts', 'unknown unidentified', 'unworthy undeserving',
    'unzip open quickly', 'uptown city area', 'vaporize turn into vapor',
    'vixen female fox', 'vodka alcoholic beverage',
    'voodoo spiritual practice', 'vortex swirling mass',
    'voyeurism secret observation', 'walkway pathway', 'waltz ballroom dance',
    'wave hand movement', 'wavy having waves', 'waxy resembling wax',
    'wellspring water source', 'wheezy breathing with difficulty',
    'whiskey alcoholic drink', 'whizzing moving quickly', 'whomever whoever',
    'wimpy weak', 'witchcraft magical practice', 'wizard sorcerer',
    'woozy dizzy', 'wristwatch timepiece worn on the wrist',
    'wyvern mythical creature', 'xylophone musical instrument',
    'yachtsman boat owner', 'yippee expression of joy', 'yoked paired',
    'youthful young', 'yummy delicious', 'zephyr gentle breeze',
    'zigzag winding pattern', 'zigzagging moving in a zigzag', 'zilch nothing',
    'zipper fastener', 'zodiac astrological signs', 'zombie undead creature'
]
